### ISSUE TITLE
CodeAction popup window: Buffer with this name already exists

### ISSUE THREAD

**Issue by merq312** [weilbith/nvim-code-action-menu#3]
I get this error when I run CodeActionMenu on any line with an available code action (no error for the popup that says "No code actions available!") . The popup shows up just fine once I dismiss the error. 

```
Error detected while processing CursorMoved Autocommands for "<buffer=23>":
E5108: Error executing lua ...action-menu\lua\code_action_menu\windows\base_window.lua:43: Vim:E95: Buffer with this name already exists
```

**Comment by weilbith** [comment]
Hmm. I know this issue. In fact this means that the menu was open once and the buffers got not wiped correctly when it closed again. I thought I fixed it with 1b24a865e7110a0007dd44c3ad5cf3729d132c30. But apparently that is not good enough for all cases. I need to think about how to make this better working.
Could you just quickly confirm that your `HEAD` includes the above commit? Just to be 100% sure.

**Comment by weilbith** [comment]
Could you please try #6 and tell me if it fixes your issue?

**Comment by merq312** [comment]
Yup I have that commit.

Also my bad, the diff view popup doesn't actually show once I dismiss the error. I can see the other two popups.

I'm running this on windows10, neovim 5.0. I pulled my config (the exact same one) into Arch (also on 5.0) and it works perfectly! So I guess this is somehow a windows related bug?

I pulled your most recent commit as well, doesn't fix the problem on windows.

My versions:

Windows10
NVIM v0.5.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

Arch
NVIM v0.5.0
Build type: Release
LuaJIT 2.0.5

**Comment by weilbith** [comment]
It works on Arch but not on Windows? 😱 
That is really awkward. I have no experience with NeoVim on Windows at all. So unfortunately I don't know about any differences here. But it would wonder me.

Could you please check one thing for me before I remove buffer names: when you get this error, close the menu again and then do a `:ls!`. Please copy the output here.

**Comment by weilbith** [comment]
So either something on the closing is broken or the it tries to open it twice.

**Comment by merq312** [comment]
I played around a bit more and there's actually at least one more issue on windows. The error I get is

`Error detected while processing CursorMoved Autocommands for "<buffer=3>":
E5108: Error executing lua ...ode_action_menu\lsp_objects\edits\text_document_edit.lua:178: bad argument #1 to 'find' (string expected, got nil)`

This seems to happen when there's more than one possible code action. Note that once the error is dismissed, I can still select and apply the code action. Still no diff view though.

Normally, neovim configuration and plugins are perfectly cross compatible across windows and linux so I'm really confused about this. Previously, the only thing that was (and still is) broken on windows but not on linux is the treesitter cpp parser (but that has some obvious reasons). I've never had a lua plugin break only on windows before.

**Comment by weilbith** [comment]
Ah, your `find` issue is related to that you don't have a `HOME` environment variable set.
Sorry, I really always ignore Windows and just care about Linux and MacOS (if at all). Please help me how to improve here. How does Windows define its home directory of the user? 🤔 
I could also just skip this and take just the absolute path if the environment variable is empty. 🤔

**Comment by weilbith** [comment]
> Could you please check one thing for me before I remove buffer names: when you get this error, close the menu again and then do a :ls!. Please copy the output here.

Could you still try this please? 🙃

**Comment by merq312** [comment]
I most certainly have HOME set. find works differently on windows though, so I think that explains it actually.

Here's the ls! output
```
  1 %a   ".\src\main.rs"                line 2
  2u h-  "NvimTree"                     line 0
  7u h-  "CodeActionMenuDiff"           line 0
 10u h   "[Scratch]"                    line 0

**Comment by weilbith** [comment]
> I most certainly have HOME set. find works differently on windows though, so I think that explains it actually.

Are you sure? Your error message points exactly to [this line](https://github.com/weilbith/nvim-code-action-menu/blob/3cd424404ad8dc16681de85d3588b027e49adb88/lua/code_action_menu/lsp_objects/edits/text_document_edit.lua#L178) and blames the `home_directory` variable.
Please run `:lua print(os.getenv("HOME"))` to very that. Else I'm very confused by your error...

> Here's the ls! output
> 
> ```
>   1 %a   ".\src\main.rs"                line 2
>   2u h-  "NvimTree"                     line 0
>   7u h-  "CodeActionMenuDiff"           line 0
>  10u h   "[Scratch]"                    line 0
> ```

Alright, yes the cleanup does not work. So let me try to remove it and then you can checkout the bugfix branch again.

**Comment by merq312** [comment]
You're right, lua doesn't detect HOME for some reason (prints nil). That's really odd because it is correctly set in my environment variables.

**Comment by weilbith** [comment]
Okay I fixed the `HOME` issue so that the code is secure in case the variable can not be found. This means it will also fall back to the full absolute path as it was before. So the code is stable, but I guess you still wanna check how you can make it work. Unfortunately that is not an issue of this plugin.

The second part or rather the original issue here should be also fixed. I finally removed the buffer naming. It wasn't necessary for functionality and I really don't know how to overcome this issue else. I can't add more functionality to ensure these buffers are always cleaned up correctly. Or everything I could do wouldn't be nice or worth it, so I just removed it. Please give the PR another try and tell me if it works so I can merge it.

Thanks for you patients to help me debugging this. 🙏🏾

**Comment by merq312** [comment]
Yup it works now! Both errors are gone.
